import type { CSSProperties, ReactNode } from 'react'
import { Icon } from './Icons'

/* ---- chat thread ------------------------------------------------------- */

export type ChatMessage = {
  from: 'in' | 'out'
  text: string
  meta?: string
  marks?: string[]
}

function withMarks(text: string, marks: string[] | undefined) {
  if (!marks || marks.length === 0) return text
  const pattern = new RegExp(`(${marks.map((m) => m.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')).join('|')})`, 'g')
  const parts = text.split(pattern)
  return parts.map((part, i) =>
    marks.includes(part) ? (
      <mark key={i}>{part}</mark>
    ) : (
      <span key={i}>{part}</span>
    ),
  )
}

export function ChatThread({ messages }: { messages: ChatMessage[] }) {
  return (
    <div className="thread">
      {messages.map((m, i) => (
        <div
          key={i}
          className={`bubble bubble--${m.from}`}
          style={{ '--bi': i } as CSSProperties}
        >
          <span>{withMarks(m.text, m.marks)}</span>
          {m.meta ? <span className="bubble__meta">{m.meta}</span> : null}
        </div>
      ))}
    </div>
  )
}

/* ---- structured order -------------------------------------------------- */

export type OrderLine = {
  name: string
  qty: number
  price: string
  meta: string[]
  updated?: boolean
}

export function OrderCard({
  id,
  status,
  statusTone = 'draft',
  lines,
  total,
  action,
}: {
  id: string
  status: string
  statusTone?: 'draft' | 'review' | 'paid'
  lines: OrderLine[]
  total: string
  action?: ReactNode
}) {
  return (
    <div className="order-card">
      <div className="order-card__head">
        <span className="order-card__id">{id}</span>
        <span className={`status status--${statusTone}`}>{status}</span>
      </div>
      <div className="order-card__rows">
        {lines.map((line, i) => (
          <div key={i} className={`order-row${line.updated ? ' is-updated' : ''}`}>
            <div className="order-row__main">
              <div className="order-row__name">
                {line.name} <span className="muted">× {line.qty}</span>
              </div>
              <div className="order-row__meta">
                {line.meta.map((m) => (
                  <span key={m} className="chip">
                    {m}
                  </span>
                ))}
              </div>
            </div>
            <div className="order-row__price">{line.price}</div>
          </div>
        ))}
      </div>
      <div className="order-card__foot">
        <span>Total payable</span>
        <span className="order-card__total">{total}</span>
        {action}
      </div>
    </div>
  )
}

/* ---- invoice ------------------------------------------------------------ */

export function Invoice({
  invoiceNo,
  customer,
  rows,
  subtotal,
  tax,
  total,
}: {
  invoiceNo: string
  customer: string
  rows: { item: string; qty: number; amount: string }[]
  subtotal: string
  tax: string
  total: string
}) {
  return (
    <div className="invoice">
      <div className="invoice__head">
        <div>
          <div className="invoice__title">Tax invoice</div>
          <div className="muted" style={{ fontSize: '0.875rem' }}>
            {invoiceNo} · Auto-generated by OrderMind
          </div>
        </div>
        <div style={{ textAlign: 'right', fontSize: '0.875rem' }}>
          <div className="muted">Billed to</div>
          <div>{customer}</div>
        </div>
      </div>

      <table className="invoice__table">
        <thead>
          <tr>
            <th scope="col">Item</th>
            <th scope="col">Qty</th>
            <th scope="col">Amount</th>
          </tr>
        </thead>
        <tbody>
          {rows.map((r) => (
            <tr key={r.item}>
              <td>{r.item}</td>
              <td>{r.qty}</td>
              <td>{r.amount}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <div className="invoice__sums">
        <div>
          <span>Subtotal</span>
          <span>{subtotal}</span>
        </div>
        <div>
          <span>GST (5%)</span>
          <span>{tax}</span>
        </div>
        <div>
          <span>Total</span>
          <span>{total}</span>
        </div>
      </div>
    </div>
  )
}

/* ---- JSON state --------------------------------------------------------- */

function colorize(text: string) {
  const parts = text.split(/("(?:[^"\\]|\\.)*")/g)
  return parts.map((part, i) => {
    if (i % 2 === 0) return <span key={i}>{part}</span>
    const isKey = /^\s*:/.test(parts[i + 1] ?? '')
    return (
      <span key={i} className={isKey ? 'k' : 's'}>
        {part}
      </span>
    )
  })
}

export function StatePanel({
  lines,
}: {
  lines: (string | { text: string; changed?: boolean })[]
}) {
  const normalized = lines.map((l) => (typeof l === 'string' ? { text: l } : l))
  return (
    <div className="state-panel">
      <div className="state-panel__bar">
        <Icon name="code" size={14} />
        <span>order_state.json</span>
      </div>
      <div className="state-panel__body">
        {normalized.map((l, i) => (
          <div key={i} className={`state-line${l.changed ? ' is-changed' : ''}`}>
            {colorize(l.text)}
          </div>
        ))}
      </div>
    </div>
  )
}
